package dev.charaly.runtime.presentation

import java.util.Locale

/**
 * LOCALISATION FOR THE RUNTIME MODULE.
 *
 * ## Why the presenters need their own catalogue
 *
 * `charaly-runtime` is a plain Kotlin/JVM library. It cannot call `Context.getString`, so a
 * presenter there has no Android resource to read. Before this file every presenter
 * therefore hardcoded English, which made the whole presentation layer untranslatable.
 *
 * Rather than move presentation into the app module - which would cost the ability to unit
 * test a screen's copy on a JVM in milliseconds - the runtime carries its own catalogue and
 * the app tells it which language is active.
 *
 * ## The contract
 *
 * * Every user-visible string a presenter produces goes through [t].
 * * Every key exists in **every** supported language. `LocaleTest` asserts it, so a key
 *   added to [TR] and forgotten in [EN] (or the reverse) fails the build rather than
 *   silently rendering English in a Turkish app.
 * * Formatting is `String.format` with positional arguments, so a language is free to
 *   reorder them. Turkish does exactly that in several places ("%1$s adresinde %2$s").
 * * An unknown key returns the key itself rather than an empty string. A blank label is
 *   invisible in review and obvious on a device.
 *
 * ## Not for developer or log strings
 *
 * Class names, JSON keys, prompts and diagnostics stay in English and stay hardcoded. They
 * are never shown to a player, and translating them would make bug reports harder to read
 * without making the product better.
 */
object Loc {

    /** Every language this build ships. */
    val SUPPORTED = listOf("en", "tr")

    private var language: String = "en"

    /**
     * Selects the active language.
     *
     * Accepts what Android hands over: `tr`, `tr-TR`, `tr_TR`. Anything unknown falls back
     * to English rather than rendering blanks, because a device set to a language Charaly
     * does not ship must still produce a usable app.
     */
    fun use(tag: String) {
        val normalised = tag.substringBefore('-').substringBefore('_').lowercase(Locale.ROOT)
        language = if (normalised in SUPPORTED) normalised else "en"
    }

    /** The active two-letter language code. */
    fun code(): String = language

    /** Restores English. Used by tests so one test cannot leak into the next. */
    fun reset() {
        language = "en"
    }

    /**
     * A localised string.
     *
     * Falls back through: requested language -> English -> the key. That chain means a
     * partially translated language degrades to English per string rather than to nothing.
     */
    fun t(key: String, vararg args: Any?): String {
        val template = catalogue[language]?.get(key)
            ?: EN[key]
            ?: key
        if (args.isEmpty()) return template
        return runCatching { String.format(Locale.ROOT, template, *args) }.getOrDefault(template)
    }

    /** True when a key exists, in the active language or in English. Used by the locale test. */
    fun has(key: String): Boolean = EN.containsKey(key) || TR.containsKey(key)

    /** Every key the catalogue knows about, in English. */
    fun keys(): Set<String> = EN.keys

    private fun catalogueFor(code: String): Map<String, String>? = when (code) {
        "tr" -> TR
        else -> null
    }

    private val catalogue: Map<String, Map<String, String>> by lazy {
        mapOf("tr" to TR)
    }
}

// ---------------------------------------------------------------------------
// English - the reference catalogue. Every key in the app exists here.
// ---------------------------------------------------------------------------

private val EN: Map<String, String> = mapOf(
    // ---- navigation -------------------------------------------------------
    "nav.home" to "Home",
    "nav.worlds" to "Worlds",
    "nav.chat" to "Stage",
    "nav.library" to "Library",
    "nav.settings" to "Settings",
    "nav.models" to "Models",
    "nav.back" to "Back",

    // ---- common actions --------------------------------------------------
    "action.continue" to "Continue",
    "action.cancel" to "Cancel",
    "action.retry" to "Retry",
    "action.dismiss" to "Dismiss",
    "action.back" to "Back",
    "action.change" to "Change",
    "action.import" to "Import",
    "action.import_gguf" to "Import GGUF",
    "action.choose_model" to "Choose a model",
    "action.open_models" to "Open Models",
    "action.step_in" to "Start the story",
    "action.open_settings" to "Settings",
    "action.browse_worlds" to "Browse all worlds",
    "action.find_world" to "Find a world",
    "action.leave_story" to "Leave the story",
    "action.scene_details" to "Scene details",
    "action.previous_step" to "Previous step",
    "action.ways_of_acting" to "Ways of acting",
    "action.close_ways" to "Close ways of acting",
    "action.back_to_story" to "Back to the story",
    "action.import_character" to "Import Character",
    "action.import_another" to "Import another character",
    "action.see_all" to "See all",
    "action.stop" to "Stop",
    "action.retry_generation" to "Generate again",

    // ---- home -------------------------------------------------------------
    "home.worlds_header" to "Worlds",
    "home.worlds_caption" to "%1${'$'}d to step into",
    "home.stories_header" to "Your stories",
    "home.continuation" to "Continue",
    "home.model_ready_pill" to "Ready",
    "home.model_choose_pill" to "Choose",
    "home.subline_continue" to "Something is waiting for you.",
    "home.subline_worlds" to "%1${'$'}d worlds to step into.",
    "home.greeting_morning" to "Good morning",
    "home.greeting_afternoon" to "Good afternoon",
    "home.greeting_evening" to "Good evening",
    "home.greeting_night" to "Good night",

    // ---- worlds -----------------------------------------------------------
    "worlds.title" to "Worlds",
    "worlds.search" to "Search worlds",
    "worlds.clear_filters" to "Clear filters",
    "worlds.empty_title" to "No worlds here yet.",
    "worlds.empty_body" to "Worlds you open will appear here.",

    // ---- story setup ------------------------------------------------------
    "setup.step.scenario.title" to "Choose an opening",
    "setup.step.scenario.subtitle" to "Every world has more than one way in",
    "setup.step.persona.title" to "Choose your role",
    "setup.step.persona.subtitle" to "Who you are inside this world",
    "setup.step.cast.title" to "Choose your cast",
    "setup.step.cast.subtitle" to "Who is already in the room",
    "setup.step.review.title" to "Review",
    "setup.step.review.subtitle" to "One last look before you step in",
    "setup.continue" to "Continue",
    "setup.enter" to "Step in",
    "setup.the_voice" to "The voice",
    "setup.no_model_bound" to "No model bound",
    "setup.you_are" to "You are",
    "setup.where" to "Where",
    "setup.who_is_there" to "Who is there",
    "setup.chosen" to "Chosen",
    "setup.no_scenarios_title" to "This world has no openings.",
    "setup.no_scenarios_body" to "A pack needs at least one starting scenario before a story can begin here.",
    "setup.no_personas_title" to "No roles to choose from.",
    "setup.no_personas_body" to "This world has not authored any personas, so there is nothing to step in as.",
    "setup.world_missing_title" to "This world is not here.",
    "setup.world_missing_body" to "It may have been removed from this device.",
    "setup.imported_characters" to "Your imported characters",
    "setup.bring_your_own" to "Bring someone of your own",

    // ---- model state ------------------------------------------------------
    "model.none_installed" to "No model installed",
    "model.needs_local" to "Charaly needs a local model",
    "model.not_installed" to "Not installed",
    "model.not_loaded" to "Not loaded",
    "model.ready" to "Ready",
    "model.loading" to "Loading",
    "model.loaded" to "Loaded",
    "model.installed" to "Installed",
    "model.could_not_load" to "Could not load",
    "model.local_meta" to "Local · %1${'$'}s",
    "model.ready_first_use" to "Ready — it will load the first time you write",
    "model.imported" to "Imported",
    "model.downloaded" to "Downloaded",
    "model.imported_ok" to "Installed %1${'$'}s",
    "model.no_model_yet" to "No model installed yet. Import a GGUF to generate replies.",
    "model.missing_for_story" to "The model for this story is no longer on this device.",
    "model.unsupported_arch" to "Unsupported architecture",
    "model.invalid_gguf" to "This file is not a valid GGUF model",
    "model.file_missing" to "The model file is missing",
    "model.load_failed" to "This model could not be loaded",
    "model.continue_allowed" to "You can start the story",
    "model.continue_blocked" to "This story cannot run until a usable model is available",

    // ---- model library ---------------------------------------------------
    "models.title" to "Models",
    "models.library" to "Model Library",
    "models.your_models" to "On this device",
    "models.explore" to "Explore models",
    "models.choose_prompt" to "Choose a local model to bring your worlds to life.",
    "models.import_hint" to "Import a GGUF you already have. It never leaves this device.",
    "models.offline" to "You're offline.",
    "models.offline_action" to "Installed models still work",
    "models.retry_search" to "Retry",
    "models.clear_search" to "Clear search",
    "models.use" to "Use",
    "models.delete" to "Delete",
    "models.verify" to "Verify",
    "models.measure" to "Measure",
    "models.not_measured" to "Not measured",
    "models.architecture" to "Architecture",
    "models.quantization" to "Quantization",
    "models.context" to "Context",
    "models.size" to "Size",
    "models.verified" to "Verified",
    "models.not_verified" to "Not verified",
    "models.yes" to "Yes",
    "models.detail" to "Model",
    "models.choose_local_body" to "Charaly speaks with a model on this device. Nothing is sent anywhere.",

    // ---- chat -------------------------------------------------------------
    "chat.needs_model" to "This story needs a local model before it can continue.",
    "chat.needs_model_detail" to "Pick a GGUF on this device to continue.",
    "chat.loading_model" to "Getting the model ready…",
    "chat.composer_say_hint" to "Say or do something…",
    "chat.composer_open_hint" to "Say something, or watch what happens.",
    "chat.stopped" to "Stopped",
    "chat.failed" to "Something interrupted the scene",
    "chat.failure_open_models" to "Choose a model",
    "chat.opening_title" to "You are in %1${'$'}s",
    "chat.opening_title_generic" to "The scene is about to begin",
    "chat.opening_body" to "%1${'$'}s is here. Say something, or watch what happens.",
    "chat.opening_body_generic" to "Say something, or watch what happens.",
    "chat.there_here" to "Here",
    "chat.there_nearby" to "Nearby",
    "chat.there_elsewhere" to "Elsewhere",
    "chat.day" to "Day %1${'$'}d",

    // ---- settings ---------------------------------------------------------
    "settings.title" to "Settings",
    "settings.app" to "App",
    "settings.ai" to "Local AI",
    "settings.offline" to "Offline",
    "settings.language" to "Language",
    "settings.language_english" to "English",
    "settings.language_turkish" to "Türkçe",
    "settings.dark" to "Dark",
    "settings.dark_caption" to "Charaly is designed to be read at night.",
    "settings.reduce_motion" to "Reduce motion",
    "settings.reduce_motion_caption" to "Transitions stop travelling. Content still changes.",
    "settings.build_world" to "Build a world",
    "settings.back" to "Back",

    // ---- empty states / errors -------------------------------------------
    "empty.no_stories_title" to "No stories yet",
    "empty.no_stories_body" to "Step into a world to begin one.",
    "empty.stage_missing_title" to "No story open",
    "empty.stage_missing_body" to "Open a story from your library to read it here.",
    "error.no_character" to "Nobody is available to talk in this scene yet.",
    "error.no_scene" to "The scene could not be placed. Move somewhere else first.",
    "error.generation_cancelled" to "Generation stopped.",
    "error.persistence" to "That change could not be saved on this device.",
    "error.too_large_model" to "This model may exceed the available device memory.",
    "error.generic" to "Something went wrong.",
    "error.import_failed" to "That file could not be imported.",
    "error.model_not_found" to "The model file could not be found.",
    "error.invalid_model" to "That file is not a valid GGUF model.",
    "error.out_of_memory" to "Not enough memory to load this model.",
    "error.unsupported_engine" to "Local inference is not available in this build.",
    "error.generation_failed" to "The local model stopped unexpectedly.",
    "error.context_exhausted" to "The model ran out of room for this scene.",
    "error.too_long" to "That reply was too long for this model to finish.",
    "error.needs_more_memory" to "The model needs more memory than this device has free.",
    "error.model_could_not_finish" to "The local model could not finish that reply.",
    "error.unexpected" to "The scene stopped unexpectedly.",
    "error.model_not_fetched" to "That model could not be fetched.",
    "error.import_partial" to "That file was not copied completely. Nothing was changed.",
    "error.import_unreadable" to "That file could not be read from your device.",
    "error.no_space" to "There is not enough free space on this device.",
    "model.importing" to "Importing\u2026",
    "model.importing_detail" to "Copying the file to this device. Large models take a while.",
    "model.verifying" to "Checking\u2026",
    "model.verifying_detail" to "Reading the model header.",
    "error.model_not_in_library" to "That file is no longer on the model library.",
    "error.library_unreachable" to "The model library could not be reached.",
    "error.network_blocked" to "The model library could not be reached.",

    // ---- accessibility ---------------------------------------------------
    "a11y.back_to" to "Back to %1${'$'}s",
    "a11y.character_says" to "%1${'$'}s says %2${'$'}s",
    "a11y.story_moment" to "Story moment: %1${'$'}s",
    "worlds.filter_clear" to "Clear filters",
    "library.title" to "Library",
    "library.details" to "Details",
    "library.chapters" to "Chapters",
    "library.what_happened" to "What happened",
    "library.delete" to "Delete",
    "showcase.start_new" to "Start somewhere new",
    "showcase.about" to "About this world",
    "showcase.tone" to "Tone",
    "showcase.atmosphere" to "Atmosphere",
    "showcase.world" to "World",
    "showcase.genre" to "Genre",
    "showcase.rights" to "Rights",
    "showcase.content" to "Content",
    "showcase.missing_title" to "This world is not here.",
    "showcase.missing_body" to "Worlds live on this device. It may have been removed.",
    "settings.developer_mode" to "Developer mode",
    "settings.open_inspector" to "Open the inspector",
    "chat.stop" to "Stop",
    "chat.send" to "Send",
    "chat.your_line" to "Your line",
    "chat.sheet_scene" to "SCENE",
    "chat.sheet_room" to "IN THE ROOM",
    "chat.sheet_recently" to "RECENTLY",
    "chat.missing_title" to "This story is not here.",
    "chat.missing_body" to "It may have been deleted. Open another one from your library.",
    "a11y.continue_story" to "Continue %1${'$'}s",
    "a11y.back_to_library" to "Back to library",
    "a11y.back_to_worlds" to "Back to worlds",
    "models.explore" to "Explore models",
    "models.browse" to "Browse",
    "models.current" to "CURRENT MODEL",
    "models.searching" to "Searching the Hub…",
    "models.measured_summary" to "%1${'$'}d of %2${'$'}d measured on this device",
    "models.unmeasured_note" to "Unmeasured models say \"Not measured\" rather than guessing a speed.",
    "models.close_repo" to "Close %1${'$'}s",
    "models.other_files" to "%1${'$'}d other files in this repository.",
    "models.checking_repo" to "Checking %1${'$'}s…",
    "detail.what_this_is" to "What this file is",
    "detail.how_it_speaks" to "How it speaks",
    "detail.stories_using" to "Stories using this model",
    "detail.missing_title" to "That model is not on this device.",
    "detail.missing_body" to "It may have been removed, or it belongs to a different download.",
    "a11y.back_to_models" to "Back to models",
    "a11y.close_sheet" to "Close %1${'$'}s",
    "sheet.recently" to "Recently",
    "sheet.nearby" to "Nearby",
    "sheet.here_now" to "Here now",
    "sheet.right_now" to "Right now",
    "sheet.worth_knowing" to "Worth knowing",
    "sheet.still_going_on" to "Still going on",
    "sheet.no_memories_title" to "Nothing remembered yet.",
    "sheet.no_memories_body" to "Memories appear here as the story accumulates them.",
    "sheet.nobody_title" to "Nobody here yet.",
    "sheet.nobody_body" to "People arrive as the story needs them.",
    "onboarding.stories_title" to "Your stories stay with you.",
    "onboarding.stories_body" to "Conversations, memories and worlds are files on this device.",
    "onboarding.worlds_title" to "Worlds, not chats.",
    "onboarding.worlds_body" to "A world holds people, places and rules that remember what happened.",
    "onboarding.model_title" to "The model runs here.",
    "onboarding.model_body" to "Replies come from a model on your phone.",
    "import.back" to "Back",
    "import.intro_title" to "Import a character.",
    "import.intro_body" to "Choose a SillyTavern character card. Charaly reads the card, shows you what is in it, and writes nothing until you say so.",
    "import.choose_file" to "Choose a file",
    "import.choose_another" to "Choose another file",
    "import.close" to "Close",
    "import.preview_empty_title" to "Nothing to preview.",
    "import.preview_empty_body" to "The card could not be read. Choose another file.",
    "import.field_description" to "Description",
    "import.field_personality" to "Personality",
    "import.field_scenario" to "Scenario",
    "import.field_greeting" to "Greeting",
    "import.field_examples" to "Example dialogue",
    "import.field_lore" to "Lore",
    "import.field_from" to "From",
    "import.field_notes" to "Author\'s notes",
    "import.confirm" to "Import Character",
    "import.cancel" to "Cancel",
    "import.done_title" to "Character imported.",
    "import.done_body" to "%1${'$'}s is now available in every story. Pick a world and add them to the cast.",
    "import.done" to "Done",
    "models.in_use" to "In use",
    "models.use_this" to "Use this model",
    "models.recheck" to "Re-check",
    "models.remove" to "Remove this model",
    "models.bound" to "BOUND",
    "models.open" to "Open",
    "models.import_cta" to "Import a GGUF you already have",
    "models.import_gguf_action" to "Import GGUF",
    "models.empty_title" to "Choose a local model to bring your worlds to life.",
    "models.empty_body" to "Download one from the Hub, or import a GGUF from your device. Nothing is sent anywhere.",
    "models.measure" to "Measure",
    "models.remove_short" to "Remove",
    "download.pause" to "Pause",
    "download.cancel" to "Cancel",
    "models.close" to "Close",
    "models.best_fit" to "Best fit",
    "models.download" to "Download",
    "models.installed" to "Installed",
    "models.other_files_full" to "%1${'$'}d other files in this repository. They are not models.",
    "setup.world_missing_title2" to "This world is not here.",
    "setup.world_missing_body2" to "It may have been removed from this device.",
    "a11y.charaly_version" to "Charaly version %1${'$'}s",
    "settings.charaly_version" to "Charaly %1${'$'}s",
    "a11y.composer_hint" to "Message",

    // ---- model test / diagnostics ---------------------------------------
    "model-test.title" to "Model test",
    "model-test.blurb" to "Load a model and generate one real reply with it. Nothing here is simulated.",
    "model-test.action" to "Run model test",
    "model-test.running" to "Running\u2026",
    "model-test.loading" to "Loading the model into memory\u2026",
    "model-test.generating" to "Generating a real reply\u2026",
    "model-test.passed" to "The model works.",
    "model-test.failed" to "The model did not respond.",
    "model-test.model" to "Model",
    "model-test.architecture" to "Architecture",
    "model-test.size" to "File size",
    "model-test.status" to "Status",
    "model-test.load_time" to "Load time",
    "model-test.first_token" to "First token",
    "model-test.speed" to "Speed",
    "model-test.backend" to "Backend",
    "model-test.engine" to "Engine",
    "model-test.tokens" to "Tokens",
    "model-test.output" to "What it said",
    "model-test.no_model" to "No model installed. Import a GGUF first.",
    "model-test.idle" to "Not run yet.",
    "model-test.measuring" to "measuring\u2026",
    "model-test.duration_only" to "duration only, not comparable to a benchmark",
    "diagnostics.title" to "Diagnostics",
    "diagnostics.blurb" to "Check that local inference really works on this device.",
)

// ---------------------------------------------------------------------------
// Turkish
// ---------------------------------------------------------------------------

private val TR: Map<String, String> = mapOf(
    // ---- navigation -------------------------------------------------------
    "nav.home" to "Ana",
    "nav.worlds" to "Dünyalar",
    "nav.chat" to "Sahne",
    "nav.library" to "Kitaplık",
    "nav.settings" to "Ayarlar",
    "nav.models" to "Motor",
    "nav.back" to "Geri",

    // ---- common actions --------------------------------------------------
    "action.continue" to "Devam Et",
    "action.cancel" to "İptal",
    "action.retry" to "Tekrar Dene",
    "action.dismiss" to "Kapat",
    "action.back" to "Geri",
    "action.change" to "Değiştir",
    "action.import" to "İçe Aktar",
    "action.import_gguf" to "Model İçe Aktar (GGUF)",
    "action.choose_model" to "Bir model seç",
    "action.open_models" to "Modelleri Aç",
    "action.step_in" to "Hikâyeyi Başlat",
    "action.open_settings" to "Ayarlar",
    "action.browse_worlds" to "Tüm dünyalara göz at",
    "action.find_world" to "Bir dünya bul",
    "action.leave_story" to "Hikâyeden çık",
    "action.scene_details" to "Sahne ayrıntıları",
    "action.previous_step" to "Önceki adım",
    "action.ways_of_acting" to "Nasıl davranılır",
    "action.close_ways" to "Nasıl davranılır seçeneğini kapat",
    "action.back_to_story" to "Hikâyeye dön",
    "action.import_character" to "Karakter İçe Aktar",
    "action.import_another" to "Başka bir karakter ekle",
    "action.see_all" to "Tümü",
    "action.stop" to "Durdur",
    "action.retry_generation" to "Tekrar üret",

    // ---- home -------------------------------------------------------------
    "home.worlds_header" to "Dünyalar",
    "home.worlds_caption" to "%1${'$'}d dünyaya adım atın",
    "home.stories_header" to "Hikâyeleriniz",
    "home.continuation" to "Devam Et",
    "home.model_ready_pill" to "Hazır",
    "home.model_choose_pill" to "Seç",
    "home.subline_continue" to "Sizi bekleyen bir şey var.",
    "home.subline_worlds" to "%1${'$'}d dünyaya adım atabilirsiniz.",
    "home.greeting_morning" to "Günaydın",
    "home.greeting_afternoon" to "İyi günler",
    "home.greeting_evening" to "İyi akşamlar",
    "home.greeting_night" to "İyi geceler",

    // ---- worlds -----------------------------------------------------------
    "worlds.title" to "Dünyalar",
    "worlds.search" to "Dünyalarda ara",
    "worlds.clear_filters" to "Filtreleri temizle",
    "worlds.empty_title" to "Henüz dünya yok.",
    "worlds.empty_body" to "Açtığınız dünyalar burada görünür.",
    "worlds.feed_title" to "Dünya Akışı",
    "worlds.dominant" to "ÖNE ÇIKAN",
    "worlds.full" to "TAM",
    "worlds.quiet" to "SAKİN",

    // ---- story setup ------------------------------------------------------
    "setup.step.scenario.title" to "Bir açılış seçin",
    "setup.step.scenario.subtitle" to "Her dünyanın birden fazla giriş yolu vardır",
    "setup.step.persona.title" to "Rolünüzü seçin",
    "setup.step.persona.subtitle" to "Bu dünyada kimsiniz",
    "setup.step.cast.title" to "Kadroyu seçin",
    "setup.step.cast.subtitle" to "Odanın içinde kimler var",
    "setup.step.review.title" to "Gözden geçir",
    "setup.step.review.subtitle" to "İçeri girmeden önce son bir bakış",
    "setup.continue" to "Devam Et",
    "setup.enter" to "Hikâyeyi Başlat",
    "setup.the_voice" to "Konuşan",
    "setup.no_model_bound" to "Model seçilmedi",
    "setup.you_are" to "Siz",
    "setup.where" to "Nerede",
    "setup.who_is_there" to "Kimler var",
    "setup.chosen" to "Seçildi",
    "setup.no_scenarios_title" to "Bu dünyada açılış yok.",
    "setup.no_scenarios_body" to "Bir dünyada hikâye başlatabilmek için en az bir başlangıç senaryosu gerekir.",
    "setup.no_personas_title" to "Seçilebilecek rol yok.",
    "setup.no_personas_body" to "Bu dünya henüz rol yazmadı, bu yüzden içeri girebileceğiniz bir kimlik yok.",
    "setup.world_missing_title" to "Bu dünya burada değil.",
    "setup.world_missing_body" to "Bu cihazdan kaldırılmış olabilir.",
    "setup.imported_characters" to "İçe aktardığınız karakterler",
    "setup.bring_your_own" to "Kendi karakterinizi getirin",

    // ---- model state ------------------------------------------------------
    "model.none_installed" to "Model yüklü değil",
    "model.needs_local" to "Charaly bir yerel model gerektirir",
    "model.not_installed" to "Yüklü değil",
    "model.not_loaded" to "Belleğe alınmadı",
    "model.ready" to "Hazır",
    "model.loading" to "Yükleniyor",
    "model.loaded" to "Yüklendi",
    "model.installed" to "Yüklü",
    "model.could_not_load" to "Yüklenemedi",
    "model.local_meta" to "Yerel · %1${'$'}s",
    "model.ready_first_use" to "Model hazır — ilk kullanımda yükleme yapılacak",
    "model.imported" to "İçe aktarıldı",
    "model.downloaded" to "İndirildi",
    "model.imported_ok" to "%1${'$'}s yüklendi",
    "model.no_model_yet" to "Henüz model yok. Yanıt üretmek için bir GGUF içe aktarın.",
    "model.missing_for_story" to "Bu hikâyenin modeli artık bu cihazda yok.",
    "model.unsupported_arch" to "Desteklenmeyen mimari",
    "model.invalid_gguf" to "Bu dosya geçerli bir GGUF modeli değil",
    "model.file_missing" to "Model dosyası bulunamadı",
    "model.load_failed" to "Bu model yüklenemedi",
    "model.continue_allowed" to "Hikâyeyi başlatabilirsiniz",
    "model.continue_blocked" to "Kullanılabilir bir model olmadan bu hikâye başlatılamaz",

    // ---- model library ---------------------------------------------------
    "models.title" to "Modeller",
    "models.library" to "Motor Kütüphanesi",
    "models.your_models" to "Bu cihazda",
    "models.explore" to "Modelleri keşfet",
    "models.choose_prompt" to "Dünyalarınızı canlandırmak için bir yerel model seçin.",
    "models.import_hint" to "Elinizde olan bir GGUF dosyasını içe aktarın. Cihazınızdan hiçbir yere gönderilmez.",
    "models.offline" to "Çevrimdışısınız.",
    "models.offline_action" to "Yüklü modeller yine çalışır",
    "models.retry_search" to "Tekrar Dene",
    "models.clear_search" to "Aramayı temizle",
    "models.use" to "Kullan",
    "models.delete" to "Sil",
    "models.verify" to "Doğrula",
    "models.measure" to "Ölç",
    "models.not_measured" to "Ölçülmedi",
    "models.architecture" to "Mimari",
    "models.quantization" to "Kuantizasyon",
    "models.context" to "Bağlam",
    "models.size" to "Boyut",
    "models.verified" to "Doğrulandı",
    "models.not_verified" to "Doğrulanmadı",
    "models.yes" to "Evet",
    "models.detail" to "Model",
    "models.choose_local_body" to "Charaly, bu cihazdaki bir modelle konuşur. Hiçbir şey gönderilmez.",

    // ---- chat -------------------------------------------------------------
    "chat.needs_model" to "Bu hikâye devam edebilmek için bir yerel modele ihtiyaç duyuyor.",
    "chat.needs_model_detail" to "Devam etmek için bu cihazdan bir GGUF seçin.",
    "chat.loading_model" to "Model hazırlanıyor…",
    "chat.composer_say_hint" to "Bir şey söyle ya da bir şey yap…",
    "chat.composer_open_hint" to "Bir şey söyle ya da ne olacağını izle.",
    "chat.stopped" to "Durduruldu",
    "chat.failed" to "Bir şey sahneyi kesti",
    "chat.failure_open_models" to "Bir model seç",
    "chat.opening_title" to "%1${'$'}s yerindesiniz",
    "chat.opening_title_generic" to "Sahne birazdan başlıyor",
    "chat.opening_body" to "%1${'$'}s burada. Bir şey söyleyin ya da ne olacağını izleyin.",
    "chat.opening_body_generic" to "Bir şey söyleyin ya da ne olacağını izleyin.",
    "chat.there_here" to "Burada",
    "chat.there_nearby" to "Yakında",
    "chat.there_elsewhere" to "Başka yerde",
    "chat.day" to "%1${'$'}d. gün",
    "chat.scene_title" to "Sahne",
    "chat.your_move" to "Hamleniniz",
    "chat.world_is_moving" to "Dünya hareket ediyor…",

    // ---- settings ---------------------------------------------------------
    "settings.title" to "Ayarlar",
    "settings.app" to "Uygulama",
    "settings.ai" to "Yerel Yapay Zekâ",
    "settings.offline" to "Çevrimdışı",
    "settings.language" to "Dil",
    "settings.language_english" to "English",
    "settings.language_turkish" to "Türkçe",
    "settings.dark" to "Koyu tema",
    "settings.dark_caption" to "Charaly gece okunmak için tasarlandı.",
    "settings.reduce_motion" to "Hareketi azalt",
    "settings.reduce_motion_caption" to "Geçişler yer değiştirmez. İçerik yine değişir.",
    "settings.build_world" to "Bir dünya kur",
    "settings.storage" to "Depolama",
    "settings.appearance" to "Görünüm",
    "settings.story" to "Hikâye",
    "settings.text_size" to "Metin boyutu",
    "settings.auto_advance" to "Otomatik ilerle",
    "settings.narration" to "Anlatım",
    "settings.current_model" to "Geçerli model",
    "settings.model_hub" to "Model Hub",
    "settings.story_packs" to "Hikâye Paketleri",
    "settings.models" to "Modeller",
    "settings.cache" to "Önbellek",
    "settings.about" to "Hakkında",
    "settings.version" to "Charaly sürümü",
    "settings.back" to "Geri",

    // ---- empty states / errors -------------------------------------------
    "empty.no_stories_title" to "Henüz hikâye yok",
    "empty.no_stories_body" to "Bir dünyaya adım atarak başlayın.",
    "empty.stage_missing_title" to "Açık hikâye yok",
    "empty.stage_missing_body" to "Kitaplıktan bir hikâye açın, burada okuyun.",
    "error.no_character" to "Bu sahnede konuşacak kimse yok.",
    "error.no_scene" to "Sahne oluşturulamadı. Önce başka bir yere geçin.",
    "error.generation_cancelled" to "Üretim durduruldu.",
    "error.persistence" to "Bu değişiklik bu cihaza kaydedilemedi.",
    "error.too_large_model" to "Bu model cihazdaki kullanılabilir belleğin üzerine çıkabilir.",
    "error.generic" to "Bir şeyler ters gitti.",
    "error.import_failed" to "Bu dosya içe aktarılamadı.",
    "error.model_not_found" to "Model dosyası bulunamadı.",
    "error.invalid_model" to "Bu dosya geçerli bir GGUF modeli değil.",
    "error.out_of_memory" to "Bu modeli yüklemek için yeterli bellek yok.",
    "error.unsupported_engine" to "Bu sürümde yerel çıkarım kullanılamıyor.",
    "error.generation_failed" to "Yerel model beklenmedik şekilde durdu.",
    "error.context_exhausted" to "Model bu sahne için yerini doldurdu.",
    "error.too_long" to "Bu model için yanıt çok uzundu.",
    "error.needs_more_memory" to "Modelin bu cihazdaki boş belleğinden fazlasına ihtiyacı var.",
    "error.model_could_not_finish" to "Yerel model bu yanıtı tamamlayamadı.",
    "error.unexpected" to "Sahne beklenmedik şekilde durdu.",
    "error.model_not_fetched" to "Bu model getirilemedi.",
    "error.import_partial" to "Bu dosya tam olarak kopyalanamad\u0131. Hi\u00e7bir de\u011fi\u015fiklik yap\u0131lmad\u0131.",
    "error.import_unreadable" to "Bu dosya cihaz\u0131n\u0131zdan okunamad\u0131.",
    "error.no_space" to "Bu cihazda yeterli bo\u015f alan yok.",
    "model.importing" to "\u0130\u00e7e aktar\u0131l\u0131yor\u2026",
    "model.importing_detail" to "Dosya bu cihaza kopyalan\u0131yor. B\u00fcy\u00fck modeller biraz s\u00fcrer.",
    "model.verifying" to "Kontrol ediliyor\u2026",
    "model.verifying_detail" to "Model bilgisi okunuyor.",
    "error.model_not_in_library" to "Bu dosya artık model kütüphanesinde yok.",
    "error.library_unreachable" to "Model kütüphanesine ulaşılamadı.",
    "error.network_blocked" to "Model kütüphanesine ulaşılamadı.",

    // ---- accessibility ---------------------------------------------------
    "a11y.back_to" to "%1${'$'}s ekranına geri dön",
    "a11y.character_says" to "%1${'$'}s şunu söylüyor: %2${'$'}s",
    "a11y.story_moment" to "Hikâye anı: %1${'$'}s",
    "worlds.filter_clear" to "Filtreleri temizle",
    "library.title" to "Kitaplık",
    "library.details" to "Ayrıntılar",
    "library.chapters" to "Bölümler",
    "library.what_happened" to "Neler oldu",
    "library.delete" to "Sil",
    "showcase.start_new" to "Yeni bir başlangıç seç",
    "showcase.about" to "Bu dünya hakkında",
    "showcase.tone" to "Ton",
    "showcase.atmosphere" to "Atmosfer",
    "showcase.world" to "Dünya",
    "showcase.genre" to "Tür",
    "showcase.rights" to "Haklar",
    "showcase.content" to "İçerik",
    "showcase.missing_title" to "Bu dünya burada değil.",
    "showcase.missing_body" to "Dünyalar bu cihazda yaşar. Kaldırılmış olabilir.",
    "settings.developer_mode" to "Geliştirici modu",
    "settings.open_inspector" to "Tanılama panelini aç",
    "chat.stop" to "Durdur",
    "chat.send" to "Gönder",
    "chat.your_line" to "Sözünüz",
    "chat.sheet_scene" to "SAHNE",
    "chat.sheet_room" to "ODADA",
    "chat.sheet_recently" to "YAKINDA",
    "chat.missing_title" to "Bu hikâye burada değil.",
    "chat.missing_body" to "Silinmiş olabilir. Kitaplıktan başka bir tane açın.",
    "a11y.continue_story" to "%1${'$'}s hikâyesine devam et",
    "a11y.back_to_library" to "Kitaplığa geri dön",
    "a11y.back_to_worlds" to "Dünyalara geri dön",
    "models.explore" to "Modelleri keşfet",
    "models.browse" to "Gözat",
    "models.current" to "GEÇERLİ MODEL",
    "models.searching" to "Hub aranıyor…",
    "models.measured_summary" to "%2${'$'}d modelden %1${'$'}d tanesi bu cihazda ölçüldü",
    "models.unmeasured_note" to "Ölçülmemiş modeller hız uydurmak yerine \"Ölçülmedi\" der.",
    "models.close_repo" to "%1${'$'}s deposunu kapat",
    "models.other_files" to "Bu depoda %1${'$'}d başka dosya var.",
    "models.checking_repo" to "%1${'$'}s kontrol ediliyor…",
    "detail.what_this_is" to "Bu dosya ne",
    "detail.how_it_speaks" to "Nasıl konuşuyor",
    "detail.stories_using" to "Bu modeli kullanan hikâyeler",
    "detail.missing_title" to "Bu model bu cihazda yok.",
    "detail.missing_body" to "Kaldırılmış ya da farklı bir indirmeye ait olabilir.",
    "a11y.back_to_models" to "Modellere geri dön",
    "a11y.close_sheet" to "%1${'$'}s panelini kapat",
    "sheet.recently" to "Yakında",
    "sheet.nearby" to "Yakında",
    "sheet.here_now" to "Şu an burada",
    "sheet.right_now" to "Şu an",
    "sheet.worth_knowing" to "Bilmeye değer",
    "sheet.still_going_on" to "Sürenler",
    "sheet.no_memories_title" to "Henüz hiçbir şey hatırlanmadı.",
    "sheet.no_memories_body" to "Anılar hikâye ilerledikçe burada birikir.",
    "sheet.nobody_title" to "Burada henüz kimse yok.",
    "sheet.nobody_body" to "İnsanlar hikâye gerektirdiğinde gelir.",
    "onboarding.stories_title" to "Hikâyeleriniz sizde kalır.",
    "onboarding.stories_body" to "Sohbetler, anılar ve dünyalar bu cihazdaki dosyalardır.",
    "onboarding.worlds_title" to "Sohbet değil, dünyalar.",
    "onboarding.worlds_body" to "Bir dünya, ne olduğunu hatırlayan insanları, yerleri ve kuralları barındırır.",
    "onboarding.model_title" to "Model burada çalışır.",
    "onboarding.model_body" to "Yanıtlar telefonunuzdaki bir modelden gelir.",
    "import.back" to "Geri",
    "import.intro_title" to "Bir karakter içe aktar.",
    "import.intro_body" to "Bir SillyTavern karakter kartı seçin. Charaly kartı okur, içindekileri gösterir ve siz onaylayana kadar hiçbir şeyi yazmaz.",
    "import.choose_file" to "Bir dosya seç",
    "import.choose_another" to "Başka bir dosya seç",
    "import.close" to "Kapat",
    "import.preview_empty_title" to "Önizlenecek bir şey yok.",
    "import.preview_empty_body" to "Kart okunamadı. Başka bir dosya seçin.",
    "import.field_description" to "Açıklama",
    "import.field_personality" to "Kişilik",
    "import.field_scenario" to "Senaryo",
    "import.field_greeting" to "Karşılama",
    "import.field_examples" to "Örnek diyaloglar",
    "import.field_lore" to "Dünya bilgisi",
    "import.field_from" to "Kaynak",
    "import.field_notes" to "Yazarın notları",
    "import.confirm" to "Karakteri İçe Aktar",
    "import.cancel" to "İptal",
    "import.done_title" to "Karakter içe aktarıldı.",
    "import.done_body" to "%1${'$'}s artık her hikâyede kullanılabilir. Bir dünya seçip kadroya ekleyin.",
    "import.done" to "Tamam",
    "models.in_use" to "Kullanımda",
    "models.use_this" to "Bu modeli kullan",
    "models.recheck" to "Yeniden kontrol et",
    "models.remove" to "Bu modeli kaldır",
    "models.bound" to "BAĞLI",
    "models.open" to "Aç",
    "models.import_cta" to "Elinizde zaten olan bir GGUF dosyasını içe aktarın",
    "models.import_gguf_action" to "GGUF İçe Aktar",
    "models.empty_title" to "Dünyalarınızı yaşatmak için bir yerel model seçin.",
    "models.empty_body" to "Hub'dan bir tane indirin ya da cihazınızdan bir GGUF içe aktarın. Hiçbir şey gönderilmez.",
    "models.measure" to "Ölç",
    "models.remove_short" to "Kaldır",
    "download.pause" to "Duraklat",
    "download.cancel" to "İptal",
    "models.close" to "Kapat",
    "models.best_fit" to "En uygun",
    "models.download" to "İndir",
    "models.installed" to "Yüklü",
    "models.other_files_full" to "Bu depoda %1${'$'}d başka dosya var. Modeller değiller.",
    "setup.world_missing_title2" to "Bu dünya burada değil.",
    "setup.world_missing_body2" to "Bu cihazdan kaldırılmış olabilir.",
    "a11y.charaly_version" to "Charaly sürümü %1${'$'}s",
    "settings.charaly_version" to "Charaly %1${'$'}s",
    "a11y.composer_hint" to "Mesaj",

    // ---- model test / diagnostics ---------------------------------------
    "model-test.title" to "Model testi",
    "model-test.blurb" to "Bir modeli y\u00fckle ve ger\u00e7ekten bir yan\u0131t \u00fcret. Burada hi\u00e7bir \u015fey taklit edilmez.",
    "model-test.action" to "Model testini \u00e7al\u0131\u015ft\u0131r",
    "model-test.running" to "\u00c7al\u0131\u015f\u0131yor\u2026",
    "model-test.loading" to "Model belle\u011fe al\u0131n\u0131yor\u2026",
    "model-test.generating" to "Ger\u00e7ek bir yan\u0131t \u00fcretiliyor\u2026",
    "model-test.passed" to "Model \u00e7al\u0131\u015f\u0131yor.",
    "model-test.failed" to "Model yan\u0131t vermedi.",
    "model-test.model" to "Model",
    "model-test.architecture" to "Mimari",
    "model-test.size" to "Dosya boyutu",
    "model-test.status" to "Durum",
    "model-test.load_time" to "Y\u00fckleme s\u00fcresi",
    "model-test.first_token" to "\u0130lk token",
    "model-test.speed" to "H\u0131z",
    "model-test.backend" to "Arka u\u00e7",
    "model-test.engine" to "Motor",
    "model-test.tokens" to "Token",
    "model-test.output" to "S\u00f6yledi\u011fi",
    "model-test.no_model" to "Model y\u00fckl\u00fc de\u011fil. \u00d6nce bir GGUF i\u00e7e aktar\u0131n.",
    "model-test.idle" to "Hen\u00fcz \u00e7al\u0131\u015f\u0131lmad\u0131.",
    "model-test.measuring" to "\u00f6l\u00e7\u00fcl\u00fcyor\u2026",
    "model-test.duration_only" to "yaln\u0131zca s\u00fcre; \u00f6l\u00e7\u00fcmle kar\u015f\u0131la\u015f\u0131t\u0131r\u0131lamaz",
    "diagnostics.title" to "Tan\u0131lama",
    "diagnostics.blurb" to "Yerel \u00e7\u0131kar\u0131m\u0131n bu cihazda ger\u00e7ekten \u00e7al\u0131\u015f\u0131p \u00e7al\u0131\u015f\u0131mad\u0131\u011f\u0131n\u0131 do\u011frulay\u0131n.",
)